### ISSUE TITLE
メールアドレス更新フラグをリセットする処理が正しく行なわれない

### ISSUE THREAD

**Issue by FukMo10** [NIFCloud-mbaas/ncmb_js#161]
## 不具合の概要(Description of bug)

バージョン：v2.1.2  
[ここ](https://github.com/NIFTYCloud-mbaas/ncmb_js/blob/master/lib/user.js#L319)に入るはずのフラグ削除処理が誤って[ここ](https://github.com/NIFTYCloud-mbaas/ncmb_js/blob/master/lib/user.js#L160)に入ってしまっています。
一度メールアドレスをsetすると、以降updateのたびに更新がかかってしまうので修正をお願いします。

**Comment by hocnguyen** [comment]
@ykokw 
I am sorry about this issue.
I had fixed this issue and create a pull request with fix/logout_expired_token  branch.
Please review at https://github.com/NIFTYCloud-mbaas/ncmb_js/pull/174
