### ISSUE TITLE
データ保存時にsetIncrementを指定するとオブジェクト型で保存される

### ISSUE THREAD

**Issue by goofmint** [NIFCloud-mbaas/ncmb_js#163]
## 不具合の概要(Description of bug)
- SDKのバージョン(SDK version)  
  2.1.1
- 不具合が発生した環境(Environment requirement)  
  node.js 5.4.0
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)  
  下記にて。

```
var Increment = ncmb.DataStore("Increment");
var item = new Increment;
item.setIncrement("increment", 1); // 1ずつ増加
item.save()
  .then(function(i) {
    console.log(i)
  })
```

のようなコードを実行すると、

```
{"__op":"Increment","amount":1}
```

といったデータで保存されます。このカラムにさらに保存しようとするとDBエラーになります。

**Comment by ncmbsdk** [comment]
saveメソッドの代わりに、保存済みのオブジェクトに対してupdateメソッドを利用することで
incrementを行うことが可能です。

サンプルコード（updateメソッドを利用できるのは保存済みオブジェクトに対してなので、saveメソッドを最初に呼び出しています）

```
var Increment = ncmb.DataStore("Increment");
var item = new Increment;
item.set("message", "test")
    .save()
    .then(function(i) {
        item.setIncrement("increment", 1); // 1ずつ増加
        item.update()
            .then(function(i) {
                  console.log(i)
            }).catch(console.error);
    }).catch(console.error);
```

saveメソッドでも利用できるような改修も検討してまいります。
