### ISSUE TITLE
mp3,mp4拡張子のファイルがダウンロードできない

### ISSUE THREAD

**Issue by ncmbadmin** [NIFCloud-mbaas/ncmb_js#208]
## 背景

node.jsにて画像ファイル（jpgやpng）はダウンロード出来るが、mp3ファイルはダウンロード出来ないという問い合わせ。ちなみに・・・

mp3ファイルの拡張子をjpgに変えて試したところ、ダウンロード出来た。 
jpgファイルの拡張子をmp3に変えたところ、ダウンロード出来なかった。

とご連絡いただいています。

また、「ダウンロードできない」という表現について。「プログラムの実行時間がある程度かかっており、データは転送されているような動きが見られるので、正確には正常に保存できないという表現が正しいかもしれない。」 とのことでした。
より詳細は、ユーザーコミュニティ投稿内容もご参照ください。
ユーザーコミュニティ投稿：
https://github.com/NIFCloud-mbaas/UserCommunity/issues/842

## 問題点
- nodejsでmp3, mp4ダウンロードできない現象

**Comment by gs0zk1** [comment]
#211 のp-rにて対応が完了しましたので、クローズいたします。
