### ISSUE TITLE
Could I get a Typescript Definition file for this SDK ?

### ISSUE THREAD

**Issue by capra314cabra** [NIFCloud-mbaas/ncmb_js#228]
I have looked for a Typescript Definition file for this NCMB SDK but it's not found in this repo.
I want to use it in the project which currently works on Typescript so I would appreciate it if you could create the file.

**Comment by ncmbsupport** [comment]
Thank you for your comment. We are sorry that we do not do support user in this repository so if you have any question, feel free to post in our [User Community](https://github.com/NIFCloud-mbaas/UserCommunity/issues).
We have the same question and answer about Typescript usage here (in Japanese), so please have a check.
https://github.com/NIFCloud-mbaas/UserCommunity/issues/1046

Thank you and best regards.
