### ISSUE TITLE
ncmbの内部に脆弱性がある

### ISSUE THREAD

**Issue by ldiago** [NIFCLOUD-mbaas/ncmb_js#249]
次のコマンドを使用してncmbをインストールした後
npm install ncmb -S

ncmbのqs依存関係の脆弱性に関する次の情報を受け取りました。

また、次のコマンドを使用して解決しようとしましたが、うまくいきませんでした。
npm audit fix --force
            
どうすれば よろしい です か

![image001](https://user-images.githubusercontent.com/2766845/76285750-d6427800-62e3-11ea-9126-3ceef6db3bc3.png)

**Comment by ncmbadmin** [comment]
お世話になっております、issueをいただき、ありがとうございます。

いただいた内容について、こちら側でも再現いたしましたので、
該当ライブラリのバージョンアップを検討させていただきます。
順次、優先付けをおこなったうえで対応いたしますので、
今しばらくお待ちいただきますようお願いいたします。
対応次第、こちらの issue にて報告いたします。

今後とも、mobile backend どうぞよろしくお願いいたします。
