### ISSUE TITLE
ログインせずにユーザを削除するとエラーとなります

### ISSUE THREAD

**Issue by inoueyuta** [NIFCLOUD-mbaas/ncmb_js#259]
## 不具合の概要(Description of bug)

- SDKのバージョン(SDK version)：v3.1.0
- 不具合が発生した環境(Environment requirement)：Cordova+Android, iOS
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
```
new NCMB(appKey, clientKey).User.fetchAll()
            .then(function(results) {
                for (var i = 0; i < results.length; i++) {
                    var object = results[i];
                    object.delete()
                        .then(function(data) {
                            console.log("delete success data: " + data);
                        })
                        .catch(function(err) {
                            console.log("delete error: " + err);
                        });
                }

            })
            .catch(function(err) {
                console.log("catch error : " + err.message);
                console.log("catch error stack: " + err.stack);
            });
```
- 実行ログ
```
catch error : Cannot read property 'objectId' of null
index.js:46 catch error stack: TypeError: Cannot read property 'objectId' of null
    at e.delete (file:///android_asset/www/js/ncmb.min.js:438:5430)
    at file:///android_asset/www/js/index.js:34:34
```

**Comment by inoueyuta** [comment]
エラーの行数から、下の箇所のUser.getCurrentUser()がnullとなっています。
https://github.com/NIFCLOUD-mbaas/ncmb_js/blob/master/lib/user.js#L345  

v3.0.0では、本現象は発生しませんでした。

**Comment by ncmbadmin** [comment]
お世話になっております、issue作成いただき、ありがとうございます。

順次、#260 も合わせて優先付けを行ったうえで対応いたしますので、
今しばらくお待ちいただきますようお願いいたします。
対応次第、こちらの issue にて報告いたします。

今後とも、mobile backend をどうぞよろしくお願いいたします。

**Comment by ncmbadmin** [comment]
お世話になっております。
本 issue の 改修が完了し v3.1.1 にてリリース済みです。
ご報告ありがとうございました。

改修済みのSDKは以下のリリースページにてご確認ください。
https://github.com/NIFCLOUD-mbaas/ncmb_js/releases

今後とも、mobile backend をどうぞよろしくお願いいたします。
