### ISSUE TITLE
File uploadでmp4(12MB)をアップしようとすると"went really wrong"となりアップできません。どなたかお知恵を頂きたくよろしくお願いいたします。当方初心者です。

### ISSUE THREAD

**Issue by AISTARWORKS** [NIFCLOUD-mbaas/ncmb_js#266]
SDKの改善にご協力いただきありがとうございます。  
(Thank you for your support our SDK.)

SDKの不具合を報告する場合は、以下の項目を確認してください。  
(If you want to report a bug of the SDK, please confirm the following terms.)

- サンプルコードにAPIキーや個人情報が含まれていないか (The sample code does not include credential information?)
- 同じバグをすでに誰かが報告していてOpenになっているissueはないか (This bug is not being reported?)

## 不具合の概要(Description of bug)

- SDKのバージョン(SDK version)
- 不具合が発生した環境(Environment requirement)
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
- エラーメッセージ(Error messages)

**Comment by ncmbadmin** [comment]
お世話になっております、issue作成いただき、ありがとうございます。

順次、優先付けを行ったうえで対応いたしますので、
今しばらくお待ちいただきますようお願いいたします。
対応次第、こちらの issue にて報告いたします。

今後とも、mobile backend をどうぞよろしくお願いいたします。

**Comment by ncmbadmin** [comment]
お世話になっております、アップロード容量上限については以下通りPlanにより違いがあります。
https://mbaas.nifcloud.com/price.htm
また質問については以下のユーザーコミュニティをご活用いただきますようお願いします。
https://github.com/NIFCLOUD-mbaas/UserCommunity

**Comment by ncmbadmin** [comment]
お世話になっております。
こちら回答済みのため、本issueをcloseさせていただきます。
今後とも、mobile backend をどうぞよろしくお願いいたします。
