### ISSUE TITLE
Travis CIからGithub Actionsへの移行(js)

### ISSUE THREAD

**Issue by watanabe-tomoya** [NIFCLOUD-mbaas/ncmb_js#271]
他SDK同様、Travis CIからGithub Actionsへの移行を行う。
`.github/workflows`配下に`js.yml`を追加する。

**Comment by thuydg** [comment]
本件対応完了したため、issueをクローズします。
v3.1.2
https://github.com/NIFCLOUD-mbaas/ncmb_js/pull/283
