### ISSUE TITLE
GET以外のスクリプト実行でクエリーが使えないのは仕様でしょうか？

### ISSUE THREAD

**Issue by goofmint** [NIFCLOUD-mbaas/ncmb_js#296]
https://github.com/NIFCLOUD-mbaas/ncmb_js/blob/60914148bf590ffc796fee906e6a4d26ae81a483/lib/request_script.js#L29

ここでGET以外はクエリーストリングを署名作成時には無視するように見えます。これは仕様でしょうか？

現在Flutter SDKにてスクリプト機能を実装中なのですが、GETリクエスト以外でクエリーを適用すると、署名作成に失敗します。スクリプトかつGETリクエスト以外ではクエリーストリングは署名作成時に使わないのでしょうか？

**Comment by goofmint** [comment]
一応自己解決しました。スクリプトの場合、独自に与えたクエリーストリングは署名生成に使わないようです（GET除く）。署名生成アルゴリズムに記述した方が良いかと思います。

https://mbaas.nifcloud.com/doc/current/rest/common/signature.html

**Comment by ncmbsupport** [comment]
貴重なご意見いただき、ありがとうございます。
ドキュメントの記載が分かりにくく、ご不便おかけし申し訳ございません。
ドキュメントの改修に参考させていただきます。
また、本件はSDKの不具合ではないため、本issueはクローズさせていただきます。
